### ISSUE TITLE
Extension Settings

### ISSUE THREAD

**Issue by jguo144** [NaturalHistoryMuseum/ckanext-contact#2]
The recipient email should be config.get('ckanext.contact.mail_to'), instead of config.get('email_to') in ckanext/contact/controller/contact.py.

**Comment by benscott** [comment]
Thanks for reporting this - I have updated it so it tries to use "ckanext.contact.mail_to" and then defaults to "email_to".

     config.get("ckanext.contact.mail_to", config.get('email_to'))
