### ISSUE TITLE
Not sending email

### ISSUE THREAD

**Issue by alantygel** [NaturalHistoryMuseum/ckanext-contact#4]
Hi,

Thanks for offering this tool! I'm having the following problem on my CKAN 2.4:
- after installing the plugin and setting the required configs, interface allow me to successfully send email, but they don't arrive on my mail box;
- I tried to fill out the smtp configurations; in this case, after pressing the send mail button, it takes a long time before giving an error.

None of both situations generates error logs.

Thank you very much,
alan

**Comment by alycejenni** [comment]
Closing because I hope this is fixed by now (if not, feel free to reopen/open a new issue)
